package uoslife.servermeeting.meetingteam.dto.request

class PayappRequestDto {
    data class PayappCheckStatusRequest(
        val userid: String,
        val linkkey: String,
        val linkval: String,
        val goodname: String,
        val price: Int,
        val recvphone: String,
        val memo: String?,
        val reqaddr: Int,
        val reqdate: String,
        val payMemo: String?,
        val payAddr: String?,
        val payDate: String,
        val payType: Int,
        val payState: Int,
        val var1: String,
        val var2: String,
        val mulNo: Int,
        val payurl: String,
        val csturl: String,
        val currency: String,
        val vccode: String?,
        val feedbacktype: Int,
        val origMulNo: Int?,
        val origPrice: Int?,
        val amountTaxable: Int?,
        val amountTaxfree: Int?,
        val amountVat: Int?,
        val buyerid: String?,
        val canceldate: String?,
        val cancelmemo: String?,
        val rebillNo: String?,
        val cardName: String?,
        val payauthcode: String?,
        val cardQuota: String?,
        val cardNum: String?,
        val vbank: String?,
        val vbankno: String?,
        val naverpoint: Int?,
        val naverpay: String?,
        val smilepaySmilecash: Int?,
        val smilepayDiscountamt: Int?
    )
}
