package uoslife.servermeeting.meetingteam.exception

import uoslife.servermeeting.global.error.exception.EntityNotFoundException
import uoslife.servermeeting.global.error.exception.ErrorCode

class CompatibilityNotFoundException : EntityNotFoundException(ErrorCode.COMPATIBILITY_NOT_FOUND)
