ALTER TABLE user
    ALTER COLUMN "id" SET DATA TYPE BIGINT;

ALTER TABLE meeting_team
    ALTER COLUMN "leader_id" SET DATA TYPE BIGINT;

ALTER TABLE payment
    ALTER COLUMN "user" SET DATA TYPE BIGINT USING;
