name: dev-Validate

on:
    pull_request:
        branches:
            - 'main'

permissions:
    id-token: write
    contents: read

env:
    PROD_PROPERTIES: ${{ secrets.CORE_PROD_PROPERTIES }}
    TEST_PROPERTIES: ${{ secrets.CORE_TEST_PROPERTIES }}

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: Clone Repository
                uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: "17"
                    distribution: "adopt" # https://github.com/actions/setup-java

            -   name: Gradle Caching
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-
            -   name: Create main-application.yml
                run: |
                    mkdir -p ./src/main/resources
                    echo "${{ env.PROD_PROPERTIES }}" > ./src/main/resources/application.yml
            -   name: Create test-application.yml
                run: |
                    mkdir -p ./src/test/resources
                    echo "${{ env.TEST_PROPERTIES }}" > ./src/test/resources/application.yml
            -   name: Build with Gradle
                run: ./gradlew clean build
